### ISSUE TITLE
The same part for delete and deploy should be refactor into one function to be re-used

### ISSUE THREAD

**Issue by JunqiZhang0** [abraverm/openengine#8]
The same part for delete and deploy should be refactor into one function to be re-used, there are some redundant code in **deploy** and **delete**, they should be refactored into something like
**execute(actionName)** where actionName can be "create/deploy, delete/destroy,update,refresh" and etc

**Comment by abraverm** [comment]
This should be easily done with the new engine.

**Comment by abraverm** [comment]
Done
